// source: msg.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.model.Msg');
goog.provide('proto.model.Msg.MessageCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.model.MsgPlain');

goog.forwardDeclare('proto.model.ComMsgType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.Msg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.model.Msg.oneofGroups_);
};
goog.inherits(proto.model.Msg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.Msg.displayName = 'proto.model.Msg';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.model.Msg.oneofGroups_ = [[11,12]];

/**
 * @enum {number}
 */
proto.model.Msg.MessageCase = {
  MESSAGE_NOT_SET: 0,
  CIPHER: 11,
  PLAINMSG: 12
};

/**
 * @return {proto.model.Msg.MessageCase}
 */
proto.model.Msg.prototype.getMessageCase = function() {
  return /** @type {proto.model.Msg.MessageCase} */(jspb.Message.computeOneofCase(this, proto.model.Msg.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.Msg.prototype.toObject = function(opt_includeInstance) {
  return proto.model.Msg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.Msg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.Msg.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, 0),
    keyprint: jspb.Message.getFieldWithDefault(msg, 2, 0),
    tm: jspb.Message.getFieldWithDefault(msg, 3, 0),
    msgtype: jspb.Message.getFieldWithDefault(msg, 4, 0),
    subtype: jspb.Message.getFieldWithDefault(msg, 5, 0),
    cipher: msg.getCipher_asB64(),
    plainmsg: (f = msg.getPlainmsg()) && proto.model.MsgPlain.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.Msg}
 */
proto.model.Msg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.Msg;
  return proto.model.Msg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.Msg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.Msg}
 */
proto.model.Msg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setKeyprint(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTm(value);
      break;
    case 4:
      var value = /** @type {!proto.model.ComMsgType} */ (reader.readEnum());
      msg.setMsgtype(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSubtype(value);
      break;
    case 11:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setCipher(value);
      break;
    case 12:
      var value = new proto.model.MsgPlain;
      reader.readMessage(value,proto.model.MsgPlain.deserializeBinaryFromReader);
      msg.setPlainmsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.Msg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.Msg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.Msg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.Msg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getKeyprint();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getTm();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getMsgtype();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getSubtype();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeBytes(
      11,
      f
    );
  }
  f = message.getPlainmsg();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.model.MsgPlain.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 version = 1;
 * @return {number}
 */
proto.model.Msg.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.model.Msg} returns this
 */
proto.model.Msg.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 keyPrint = 2;
 * @return {number}
 */
proto.model.Msg.prototype.getKeyprint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.model.Msg} returns this
 */
proto.model.Msg.prototype.setKeyprint = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 tm = 3;
 * @return {number}
 */
proto.model.Msg.prototype.getTm = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.model.Msg} returns this
 */
proto.model.Msg.prototype.setTm = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional ComMsgType msgType = 4;
 * @return {!proto.model.ComMsgType}
 */
proto.model.Msg.prototype.getMsgtype = function() {
  return /** @type {!proto.model.ComMsgType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.model.ComMsgType} value
 * @return {!proto.model.Msg} returns this
 */
proto.model.Msg.prototype.setMsgtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional int32 subType = 5;
 * @return {number}
 */
proto.model.Msg.prototype.getSubtype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.model.Msg} returns this
 */
proto.model.Msg.prototype.setSubtype = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bytes cipher = 11;
 * @return {string}
 */
proto.model.Msg.prototype.getCipher = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * optional bytes cipher = 11;
 * This is a type-conversion wrapper around `getCipher()`
 * @return {string}
 */
proto.model.Msg.prototype.getCipher_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getCipher()));
};


/**
 * optional bytes cipher = 11;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCipher()`
 * @return {!Uint8Array}
 */
proto.model.Msg.prototype.getCipher_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getCipher()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.model.Msg} returns this
 */
proto.model.Msg.prototype.setCipher = function(value) {
  return jspb.Message.setOneofField(this, 11, proto.model.Msg.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.model.Msg} returns this
 */
proto.model.Msg.prototype.clearCipher = function() {
  return jspb.Message.setOneofField(this, 11, proto.model.Msg.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.Msg.prototype.hasCipher = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional MsgPlain plainMsg = 12;
 * @return {?proto.model.MsgPlain}
 */
proto.model.Msg.prototype.getPlainmsg = function() {
  return /** @type{?proto.model.MsgPlain} */ (
    jspb.Message.getWrapperField(this, proto.model.MsgPlain, 12));
};


/**
 * @param {?proto.model.MsgPlain|undefined} value
 * @return {!proto.model.Msg} returns this
*/
proto.model.Msg.prototype.setPlainmsg = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.model.Msg.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.model.Msg} returns this
 */
proto.model.Msg.prototype.clearPlainmsg = function() {
  return this.setPlainmsg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.model.Msg.prototype.hasPlainmsg = function() {
  return jspb.Message.getField(this, 12) != null;
};


