// source: msg.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.model.MsgDownloadReply');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.MsgDownloadReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.MsgDownloadReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.MsgDownloadReply.displayName = 'proto.model.MsgDownloadReply';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.MsgDownloadReply.prototype.toObject = function(opt_includeInstance) {
  return proto.model.MsgDownloadReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.MsgDownloadReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.MsgDownloadReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    sendid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    filename: jspb.Message.getFieldWithDefault(msg, 2, ""),
    realname: jspb.Message.getFieldWithDefault(msg, 3, ""),
    filetype: jspb.Message.getFieldWithDefault(msg, 4, ""),
    hashtype: jspb.Message.getFieldWithDefault(msg, 5, ""),
    hashcode: jspb.Message.getFieldWithDefault(msg, 6, ""),
    data: msg.getData_asB64(),
    size: jspb.Message.getFieldWithDefault(msg, 8, 0),
    offset: jspb.Message.getFieldWithDefault(msg, 9, 0),
    chunksize: jspb.Message.getFieldWithDefault(msg, 10, 0),
    chunkcount: jspb.Message.getFieldWithDefault(msg, 11, 0),
    chunkindex: jspb.Message.getFieldWithDefault(msg, 12, 0),
    result: jspb.Message.getFieldWithDefault(msg, 13, ""),
    detail: jspb.Message.getFieldWithDefault(msg, 14, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.MsgDownloadReply}
 */
proto.model.MsgDownloadReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.MsgDownloadReply;
  return proto.model.MsgDownloadReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.MsgDownloadReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.MsgDownloadReply}
 */
proto.model.MsgDownloadReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSendid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRealname(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFiletype(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHashtype(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setHashcode(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSize(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOffset(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChunksize(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChunkcount(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChunkindex(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setResult(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.MsgDownloadReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.MsgDownloadReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.MsgDownloadReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.MsgDownloadReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSendid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRealname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFiletype();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHashtype();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getHashcode();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getOffset();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getChunksize();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getChunkcount();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getChunkindex();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getResult();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getDetail();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
};


/**
 * optional string sendId = 1;
 * @return {string}
 */
proto.model.MsgDownloadReply.prototype.getSendid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setSendid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string fileName = 2;
 * @return {string}
 */
proto.model.MsgDownloadReply.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string realName = 3;
 * @return {string}
 */
proto.model.MsgDownloadReply.prototype.getRealname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setRealname = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string fileType = 4;
 * @return {string}
 */
proto.model.MsgDownloadReply.prototype.getFiletype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setFiletype = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string hashType = 5;
 * @return {string}
 */
proto.model.MsgDownloadReply.prototype.getHashtype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setHashtype = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string hashCode = 6;
 * @return {string}
 */
proto.model.MsgDownloadReply.prototype.getHashcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setHashcode = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional bytes data = 7;
 * @return {string}
 */
proto.model.MsgDownloadReply.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes data = 7;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.model.MsgDownloadReply.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.model.MsgDownloadReply.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 7, value);
};


/**
 * optional int64 size = 8;
 * @return {number}
 */
proto.model.MsgDownloadReply.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setSize = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 offset = 9;
 * @return {number}
 */
proto.model.MsgDownloadReply.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setOffset = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 chunkSize = 10;
 * @return {number}
 */
proto.model.MsgDownloadReply.prototype.getChunksize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setChunksize = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 chunkCount = 11;
 * @return {number}
 */
proto.model.MsgDownloadReply.prototype.getChunkcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setChunkcount = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 chunkIndex = 12;
 * @return {number}
 */
proto.model.MsgDownloadReply.prototype.getChunkindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setChunkindex = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string result = 13;
 * @return {string}
 */
proto.model.MsgDownloadReply.prototype.getResult = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setResult = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string detail = 14;
 * @return {string}
 */
proto.model.MsgDownloadReply.prototype.getDetail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgDownloadReply} returns this
 */
proto.model.MsgDownloadReply.prototype.setDetail = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


