// source: msg.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.model.MsgUploadReq');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.MsgUploadReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.MsgUploadReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.model.MsgUploadReq.displayName = 'proto.model.MsgUploadReq';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.MsgUploadReq.prototype.toObject = function(opt_includeInstance) {
  return proto.model.MsgUploadReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.MsgUploadReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.MsgUploadReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    filename: jspb.Message.getFieldWithDefault(msg, 1, ""),
    filesize: jspb.Message.getFieldWithDefault(msg, 2, 0),
    filedata: msg.getFiledata_asB64(),
    hashtype: jspb.Message.getFieldWithDefault(msg, 4, ""),
    hashcode: msg.getHashcode_asB64(),
    filetype: jspb.Message.getFieldWithDefault(msg, 6, ""),
    sendid: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.model.MsgUploadReq}
 */
proto.model.MsgUploadReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.model.MsgUploadReq;
  return proto.model.MsgUploadReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.model.MsgUploadReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.model.MsgUploadReq}
 */
proto.model.MsgUploadReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFilesize(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFiledata(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setHashtype(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setHashcode(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setFiletype(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSendid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.model.MsgUploadReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.model.MsgUploadReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.model.MsgUploadReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.model.MsgUploadReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFilesize();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getFiledata_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getHashtype();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHashcode_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getFiletype();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSendid();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string fileName = 1;
 * @return {string}
 */
proto.model.MsgUploadReq.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgUploadReq} returns this
 */
proto.model.MsgUploadReq.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 fileSize = 2;
 * @return {number}
 */
proto.model.MsgUploadReq.prototype.getFilesize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.model.MsgUploadReq} returns this
 */
proto.model.MsgUploadReq.prototype.setFilesize = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional bytes fileData = 3;
 * @return {string}
 */
proto.model.MsgUploadReq.prototype.getFiledata = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes fileData = 3;
 * This is a type-conversion wrapper around `getFiledata()`
 * @return {string}
 */
proto.model.MsgUploadReq.prototype.getFiledata_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFiledata()));
};


/**
 * optional bytes fileData = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFiledata()`
 * @return {!Uint8Array}
 */
proto.model.MsgUploadReq.prototype.getFiledata_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFiledata()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.model.MsgUploadReq} returns this
 */
proto.model.MsgUploadReq.prototype.setFiledata = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional string hashType = 4;
 * @return {string}
 */
proto.model.MsgUploadReq.prototype.getHashtype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgUploadReq} returns this
 */
proto.model.MsgUploadReq.prototype.setHashtype = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bytes hashCode = 5;
 * @return {string}
 */
proto.model.MsgUploadReq.prototype.getHashcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes hashCode = 5;
 * This is a type-conversion wrapper around `getHashcode()`
 * @return {string}
 */
proto.model.MsgUploadReq.prototype.getHashcode_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getHashcode()));
};


/**
 * optional bytes hashCode = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getHashcode()`
 * @return {!Uint8Array}
 */
proto.model.MsgUploadReq.prototype.getHashcode_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getHashcode()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.model.MsgUploadReq} returns this
 */
proto.model.MsgUploadReq.prototype.setHashcode = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional string fileType = 6;
 * @return {string}
 */
proto.model.MsgUploadReq.prototype.getFiletype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgUploadReq} returns this
 */
proto.model.MsgUploadReq.prototype.setFiletype = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string sendId = 7;
 * @return {string}
 */
proto.model.MsgUploadReq.prototype.getSendid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.model.MsgUploadReq} returns this
 */
proto.model.MsgUploadReq.prototype.setSendid = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


